=== richardh65/bct-ace-ant-action/Diagram_Project/TCPIP/DataLibrary/SaleMessage.xsd
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://iib.tutorial/salesMessage" xmlns:sm="http://iib.tutorial/salesMessage">
  <xsd:element name="Description" type="xsd:string"/>
  <xsd:element name="Quantity" type="xsd:string"/>
  <xsd:element name="CompletionTime" type="xsd:string"/>
  <xsd:element name="Invoice">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="sm:Initial"/>
        <xsd:element ref="sm:Surname"/>
        <xsd:element maxOccurs="unbounded" ref="sm:Item"/>
        <xsd:element ref="sm:Balance"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="Trailer">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="sm:CompletionTime"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="SaleListCount" type="xsd:string"/>
  <xsd:element name="Code" type="xsd:string"/>
  <xsd:element name="Category" type="xsd:string"/>
  <xsd:element name="Port" type="xsd:string"/>
  <xsd:element name="Item">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="sm:Code"/>
        <xsd:element ref="sm:Description"/>
        <xsd:element ref="sm:Category"/>
        <xsd:element ref="sm:Price"/>
        <xsd:element ref="sm:Quantity"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="Header">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="sm:SaleListCount"/>
        <xsd:element ref="sm:Hostname"/>
        <xsd:element ref="sm:Port"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="SaleMessage">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="sm:Header"/>
        <xsd:element ref="sm:SaleList"/>
        <xsd:element ref="sm:Trailer"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="Price" type="xsd:string"/>
  <xsd:element name="SaleList">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" ref="sm:Invoice"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="Surname" type="xsd:string"/>
  <xsd:element name="Initial" type="xsd:string"/>
  <xsd:element name="Balance" type="xsd:string"/>
  <xsd:element name="Hostname" type="xsd:string"/>
</xsd:schema>

=== richardh65/bct-ace-ant-action/Diagram_Project/TCPIP/DataLibrary/TestSaleMessage.xml
<?xml version="1.0" encoding="UTF-8"?>
<sm:SaleMessage xmlns:sm="http://iib.tutorial/salesMessage" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://iib.tutorial/salesMessage SaleMessage.xsd ">
  <sm:Header>
    <sm:SaleListCount>1</sm:SaleListCount>
    <sm:Hostname>localhost</sm:Hostname>
    <sm:Port>7777</sm:Port>
  </sm:Header>
  <sm:SaleList>
    <sm:Invoice>
      <sm:Initial>J</sm:Initial>
      <sm:Surname>Smith</sm:Surname>
      <sm:Item>
        <sm:Code>12345678</sm:Code>
        <sm:Description>Cycle world - Yearly subscription</sm:Description>
        <sm:Category>Magazine subscription</sm:Category>
        <sm:Price>25</sm:Price>
        <sm:Quantity>1</sm:Quantity>
      </sm:Item>
      <sm:Item>
        <sm:Code>12345679</sm:Code>
        <sm:Description>W. Shakespear - Hamlet</sm:Description>
        <sm:Category>Books</sm:Category>
        <sm:Price>28</sm:Price>
        <sm:Quantity>1</sm:Quantity>
      </sm:Item>
      <sm:Balance>53</sm:Balance>
    </sm:Invoice>
  </sm:SaleList>
  <sm:Trailer>
    <sm:CompletionTime>12:11:15-30.12.2014</sm:CompletionTime>
  </sm:Trailer>
</sm:SaleMessage>
